image: maven:3.9.6-eclipse-temurin-21

stages:
  - build
  - test
  - quality

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

cache:
  paths:
    - .m2/repository
    - .sonar/cache

# ===== BUILD =====
build-job:
  stage: build
  script:
    - echo "Compiling the project..."
    - mvn clean compile -B

# ===== UNIT TESTS =====
unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test -B

# ===== SONARCLOUD =====
sonarcloud-check:
  stage: quality
  script:
    - echo "Running SonarCloud analysis..."
    - mvn verify sonar:sonar -B -DskipTests -DskipITs
  only:
    - main
    - merge_requests