apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-service
  namespace: yanashop
  labels:
    app: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-service
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      containers:
        - name: catalogue-service
          image: 825386256502.dkr.ecr.eu-west-3.amazonaws.com/marketplace/catalogue-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          envFrom:
            - configMapRef:
                name: catalogue-service-config
            - secretRef:
                name: catalogue-service-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15